import { afterEach, beforeAll, beforeEach, describe, expect, it } from "bun:test";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import type { AgentToolResult } from "@oh-my-pi/pi-agent-core";
import { Settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import type { ClientBridge } from "@oh-my-pi/pi-coding-agent/session/client-bridge";
import type { ToolSession } from "@oh-my-pi/pi-coding-agent/tools";
import { wrapToolWithMetaNotice } from "@oh-my-pi/pi-coding-agent/tools/output-meta";
import { ReadTool } from "@oh-my-pi/pi-coding-agent/tools/read";
import { WriteTool } from "@oh-my-pi/pi-coding-agent/tools/write";

function createSession(cwd: string, bridge?: ClientBridge): ToolSession {
	return {
		cwd,
		hasUI: false,
		getSessionFile: () => path.join(cwd, "session.jsonl"),
		getSessionSpawns: () => "*",
		getArtifactsDir: () => path.join(cwd, "artifacts"),
		allocateOutputArtifact: async () => ({ id: "artifact-1", path: path.join(cwd, "artifact-1.log") }),
		settings: Settings.isolated({ "edit.blockAutoGenerated": false, "edit.mode": "replace" }),
		enableLsp: false,
		getClientBridge: bridge ? () => bridge : undefined,
	};
}

function resultText(result: AgentToolResult): string {
	return result.content.flatMap(block => (block.type === "text" ? [block.text] : [])).join("\n");
}

describe("write tool read projection guard", () => {
	let tmpDir: string;

	beforeAll(async () => {
		await Settings.init({ inMemory: true });
	});

	beforeEach(async () => {
		tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "write-read-projection-test-"));
	});

	afterEach(async () => {
		await fs.rm(tmpDir, { recursive: true, force: true });
	});

	it.each([
		{
			name: "Showing lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60. Use :21 to continue]",
		},
		{
			name: "byte-budget Showing lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60 (50.0KB limit). Use :21 to continue]",
		},
		{
			name: "entity-labelled remaining-lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[40 more lines in notebook. Use :21 to continue]",
		},
		{
			name: "unscanned remaining-lines notice",
			sourceLines: 60,
			visibleLines: 20,
			notice: "[More lines in file (120.0KB total; not scanned to EOF). Use :21 to continue]",
		},
		{
			name: "ASCII summary elision notice",
			sourceLines: 40,
			visibleLines: 10,
			notice: "[...30ln elided; re-read needed ranges, e.g. sample.txt:11-20,31-40]",
		},
		{
			name: "stale-total notice",
			sourceLines: 65,
			visibleLines: 20,
			notice: "[Showing lines 1-20 of 60. Use :21 to continue]",
		},
	])("rejects a shorter $name projection without changing the file", async ({ sourceLines, visibleLines, notice }) => {
		const filePath = path.join(tmpDir, "sample.txt");
		const originalLines = Array.from({ length: sourceLines }, (_, index) => `line ${index + 1}`);
		const original = `${originalLines.join("\n")}\n`;
		await Bun.write(filePath, original);
		const partial = `${originalLines.slice(0, visibleLines).join("\n")}\n${notice}\n`;

		await expect(
			new WriteTool(createSession(tmpDir)).execute("call-1", { path: filePath, content: partial }),
		).rejects.toThrow("replacement ends with an omp read truncation notice and is shorter than the current source");
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("rejects the actual bounded ReadTool output without changing the file", async () => {
		const filePath = path.join(tmpDir, "round-trip.txt");
		const original = `${Array.from({ length: 60 }, (_, index) => `line ${index + 1}`).join("\n")}\n`;
		await Bun.write(filePath, original);
		const session = createSession(tmpDir);
		session.settings.set("read.defaultLimit", 20);
		const projection = resultText(
			await wrapToolWithMetaNotice(new ReadTool(session)).execute("read-1", { path: filePath }),
		);
		expect(projection).toContain("[Showing lines 1-20 of 60. Use :21 to continue]");

		await expect(new WriteTool(session).execute("write-1", { path: filePath, content: projection })).rejects.toThrow(
			"incomplete read projection",
		);
		expect(await Bun.file(filePath).text()).toBe(original);
	});

	it("compares against the ACP buffer before bridge writes", async () => {
		const filePath = path.join(tmpDir, "bridge.txt");
		const diskContent = "disk\n";
		const bufferContent = `${Array.from({ length: 65 }, (_, index) => `buffer ${index + 1}`).join("\n")}\n`;
		await Bun.write(filePath, diskContent);
		let bridgeWriteCalled = false;
		let bridgeReadCalled = false;
		const bridge: ClientBridge = {
			capabilities: { readTextFile: true, writeTextFile: true },
			readTextFile: async () => {
				bridgeReadCalled = true;
				return bufferContent;
			},
			writeTextFile: async () => {
				bridgeWriteCalled = true;
			},
		};
		const partial = `${bufferContent.split("\n").slice(0, 20).join("\n")}\n[Showing lines 1-20 of 65. Use :21 to continue]\n`;

		await expect(
			new WriteTool(createSession(tmpDir, bridge)).execute("write-bridge", { path: filePath, content: partial }),
		).rejects.toThrow("incomplete read projection");
		expect(bridgeReadCalled).toBe(true);
		expect(bridgeWriteCalled).toBe(false);
		expect(await Bun.file(filePath).text()).toBe(diskContent);
	});

	it("writes a literal read notice when the replacement does not shrink the current source", async () => {
		const filePath = path.join(tmpDir, "documentation.txt");
		const content = "Example omp output:\n[Showing lines 1-20 of 60. Use :21 to continue]\n";
		await Bun.write(filePath, "old\n");

		await new WriteTool(createSession(tmpDir)).execute("call-2", { path: filePath, content });

		expect(await Bun.file(filePath).text()).toBe(content);
	});
});
