/**
 * `cmake` configure shim for cargo builds.
 *
 * Background: audiopus_sys 0.2.2 (pinned, latest upstream) builds its vendored
 * Opus via the `cmake` crate and hardcodes `rustc-link-search={out}/lib`, but
 * its CMakeLists uses GNUInstallDirs, which installs to `lib64` on 64-bit
 * Linux. The `CMAKE_INSTALL_LIBDIR` environment variable does not seed the
 * CMake cache (verified empirically), and the sys crate accepts no defines, so
 * the only reliable lever is appending `-DCMAKE_INSTALL_LIBDIR=lib` to the
 * cmake *configure* invocation. Cargo offers no hook for that; a bare `cmake`
 * on PATH does the job because the `cmake` crate resolves the binary from the
 * environment.
 *
 * The shim execs the real cmake untouched except for configure runs
 * (identified by `-B`, which the cmake crate always passes on CMake >= 3.13),
 * so `--build`, `--install`, `-E`, and `--version` probes pass through
 * byte-identical. It is a no-op wherever pkg-config already satisfies the sys
 * crate (cmake never runs) and on Windows (which keeps its VS-path logic in
 * build-bindings.ts).
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

const SHIM_DIR = path.join(os.tmpdir(), "omp-cmake-shim");
const SHIM_PATH = path.join(SHIM_DIR, "cmake");

function shimScript(realCmake: string): string {
	const quoted = `'${realCmake.replaceAll("'", `'"'"'`)}'`;
	return `#!/bin/sh
# Generated by scripts/cmake-shim.ts — do not edit. Forces GNUInstallDirs
# installs into <prefix>/lib so vendored sys crates with a hardcoded
# {out}/lib link search (audiopus_sys) link on lib64 Linux hosts.
real_cmake=${quoted}
configure=0
for arg in "$@"; do
	case "$arg" in
		--build|--install|-E|--version|--help|-h|-P) exec "$real_cmake" "$@";;
		-B) configure=1;;
	esac
done
if [ "$configure" -eq 1 ]; then
	exec "$real_cmake" "$@" -DCMAKE_INSTALL_LIBDIR=lib
fi
exec "$real_cmake" "$@"
`;
}

let warnedNoNinja = false;

/**
 * Ensure the configure shim exists and return its directory for PATH
 * prepending, or `undefined` when no shim applies (Windows, or no cmake on
 * PATH — downstream tooling then fails with its own message).
 *
 * Safe to call repeatedly; the shim file is replaced atomically and identical
 * across calls on one host.
 */
export function ensureCmakeConfigureShim(): string | undefined {
	if (process.platform === "win32") return undefined;
	const realCmake = Bun.which("cmake");
	if (!realCmake) return undefined;
	if (process.platform === "darwin" && !Bun.which("ninja") && !warnedNoNinja) {
		warnedNoNinja = true;
		console.warn(
			"cmake-shim: ninja is not on PATH; the Makefile generator can wedge cargo on macOS (see .cargo/config.toml). `brew install ninja` is recommended.",
		);
	}
	fs.mkdirSync(SHIM_DIR, { recursive: true });
	const tmpPath = `${SHIM_PATH}.${process.pid}.tmp`;
	fs.writeFileSync(tmpPath, shimScript(realCmake), { mode: 0o755 });
	fs.renameSync(tmpPath, SHIM_PATH);
	return SHIM_DIR;
}
